# Generated by Django 5.2.7 on 2025-11-08 21:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('precioInicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.FileField(upload_to='')),
                ('fechaPublicacion', models.DateTimeField(auto_now_add=True)),
                ('fechaInicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fechaFin', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('fechaInicio',),
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfertaAnuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaOferta', models.DateTimeField(auto_now_add=True)),
                ('precioOferta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('esGanador', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeguimientoAnuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
