# Generated by Django 5.2.7 on 2025-11-09 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anuncio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='publicadoPor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anunciosPublicados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='categorias',
            field=models.ManyToManyField(to='anuncio.categoria'),
        ),
        migrations.AddField(
            model_name='ofertaanuncio',
            name='anuncio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='anuncio.anuncio'),
        ),
        migrations.AddField(
            model_name='ofertaanuncio',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='ofertaGanadora',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ofertaGanadora', to='anuncio.ofertaanuncio'),
        ),
        migrations.AddField(
            model_name='seguimientoanuncio',
            name='anuncio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='anuncio.anuncio'),
        ),
        migrations.AddField(
            model_name='seguimientoanuncio',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientosUsuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
